[package]
name = "ethereum-scripts-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
ethers = { version = "1.0.0", features = ["legacy"] }
eyre = "0.6.8"
tokio = { version = "1.23.0", features = ["full"] }
